<head>
	<title><?php echo $interface_system[1].$path_title; ?></title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<!-- Описание содержания сайта -->
	<meta name="author" content="Se Bo" />
	<meta name="copyright" content="<?php echo '&copy; 2002-'.date('Y').', Se Bo'; ?>" lang="<?php echo $language_use; ?>" />
	<meta name="description" content="<?php echo $content_description; ?>" />
	<!-- Описание от 100 до 200 слов -->
	<meta name="keywords" content="<?php echo $content_keywords; ?>" lang="<?php echo $language_use; ?>" />
	<!-- Информация для поисковых роботов -->
	<meta name="robots" content="noindex, nofollow">
	<!-- Логотип сайта -->
	<link type="image/png" rel="icon" href="<?php echo $dir; ?>img\logo.png" />
	<link type="image/x-icon" rel="shortcut icon" href="<?php echo $dir; ?>img\logo.png" />
	<!-- Bootstrap -->
	<link type="text/css" rel="stylesheet" href="<?php echo $dir; ?>css\bootstrap.css">
	<link type="text/css" rel="stylesheet" href="<?php echo $dir; ?>css\font-awesome.css">
	<link type="text/css" rel="stylesheet" href="<?php echo $dir; ?>css\index.css">
	<link type="text/css" rel="stylesheet" href="<?php echo $dir; ?>css\masonry.css">
</head>